name: Daily Hadith Sender

on:
  schedule:
    - cron: '30 1 * * *'  # Daily at 7:00 AM IST
  workflow_dispatch:       # Enables manual trigger button

jobs:
  send_hadith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Hadith Sender Script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HADITH_ROLE_ID: ${{ secrets.HADITH_ROLE_ID }}
        run: python hadith_ping.py --manual
        
